.PHONY: all clean

DST_DIR := /usr/local

all:
	@chmod a+x hddlspipe
	@echo "Success!"
clean:
	@echo "Clean is done"
install:
	@cp hddlspipe $(DST_DIR)/bin/.
	@echo ""
	@echo "Success to install hddlspipe into $(DST_DIR)/bin/."
	@echo ""
